### ISSUE TITLE
Player can disappear behind some buildings

### ISSUE THREAD

**Issue by pcbonnen** [pcbonnen/school-walker#19]
*Requestor*: Jonathan Ye

If the player moves behind some buildings (such as the pink house), the player is completely obscured by the roof. This can be a little disorienting for the player.

**Comment by rafalogorek** [comment]
Fixed in commit 54ef7c0. There are three houses still where the player will disappear for a split second when walking behind them, however, this should not be an issue. These houses couldn't be moved down much further, otherwise, it would be difficult for the player to see the paths to access these buildings because they would be moved behind other buildings.
